baseURL = "/"
theme = "remark-twemoji"
languageCode = "en-us"
title = "Site Title | NDC Sydney 2017 - Kids"
canonifyurls    = true

[params]
  name = "Dillon"
  description = "Slides for NDC Sydney 2017 - Kids"
